[package]
name = "netpod-jlabath-gcs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
tokio = { version = "1", features = ["full"] }
bendy = { version = "0.3", features = [] }
google-cloud-storage = "0.24.0"
serde_json = "1.0"